  create table
  public.teams (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    conference text not null,
    division text not null,
    constraint teams_pkey primary key (id),
    constraint teams_name_key unique (name)
  ) tablespace pg_default;

  create table
  public.positions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    role text not null,
    side text not null,
    constraint positions_pkey primary key (id)
  ) tablespace pg_default;


create table
  public.players (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    team bigint null,
    position bigint null,
    logo_url text null,
    constraint players_pkey primary key (id),
    constraint players_team_fkey foreign key (team) references teams (id),
    constraint players_position_fkey foreign key ("position") references positions (id)
  ) tablespace pg_default;


